// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type DeviceAuthSession struct {
	ID         int64          `json:"id"`
	DeviceCode string         `json:"device_code"`
	UserCode   string         `json:"user_code"`
	UserID     sql.NullInt64  `json:"user_id"`
	Approved   bool           `json:"approved"`
	Token      sql.NullString `json:"token"`
	ExpiresAt  time.Time      `json:"expires_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type File struct {
	ID                int64          `json:"id"`
	UserID            int64          `json:"user_id"`
	EncryptedFilename string         `json:"encrypted_filename"`
	FileSize          int64          `json:"file_size"`
	EncryptedKey      string         `json:"encrypted_key"`
	ShareToken        sql.NullString `json:"share_token"`
	DownloadCount     int64          `json:"download_count"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	FileData          []byte         `json:"file_data"`
}

type Log struct {
	SessionID      string         `json:"session_id"`
	IpFrom         string         `json:"ip_from"`
	IpTo           sql.NullString `json:"ip_to"`
	BandwidthBytes sql.NullInt64  `json:"bandwidth_bytes"`
	SessionStart   time.Time      `json:"session_start"`
	SessionEnd     sql.NullTime   `json:"session_end"`
}

type User struct {
	ID                int64          `json:"id"`
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	EncryptionSalt    string         `json:"encryption_salt"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	Subscriber        int32          `json:"subscriber"`
	Verified          int32          `json:"verified"`
	VerificationToken sql.NullString `json:"verification_token"`
}
