// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type File struct {
	ID                int64          `json:"id"`
	UserID            int64          `json:"user_id"`
	EncryptedFilename string         `json:"encrypted_filename"`
	FilePath          string         `json:"file_path"`
	FileSize          int64          `json:"file_size"`
	EncryptedKey      string         `json:"encrypted_key"`
	ShareToken        sql.NullString `json:"share_token"`
	DownloadCount     int64          `json:"download_count"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type Log struct {
	SessionID      string         `json:"session_id"`
	IpFrom         string         `json:"ip_from"`
	IpTo           sql.NullString `json:"ip_to"`
	BandwidthBytes sql.NullInt64  `json:"bandwidth_bytes"`
	SessionStart   time.Time      `json:"session_start"`
	SessionEnd     sql.NullTime   `json:"session_end"`
}

type User struct {
	ID             int64     `json:"id"`
	Email          string    `json:"email"`
	PasswordHash   string    `json:"password_hash"`
	EncryptionSalt string    `json:"encryption_salt"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Subscriber     int64     `json:"subscriber"`
}
