// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (user_id, encrypted_filename, file_path, file_size, encrypted_key, share_token, download_count)
VALUES (?, ?, ?, ?, ?, ?, 0)
RETURNING id, user_id, encrypted_filename, file_path, file_size, encrypted_key, share_token, download_count, created_at, updated_at
`

type CreateFileParams struct {
	UserID            int64          `json:"user_id"`
	EncryptedFilename string         `json:"encrypted_filename"`
	FilePath          string         `json:"file_path"`
	FileSize          int64          `json:"file_size"`
	EncryptedKey      string         `json:"encrypted_key"`
	ShareToken        sql.NullString `json:"share_token"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.UserID,
		arg.EncryptedFilename,
		arg.FilePath,
		arg.FileSize,
		arg.EncryptedKey,
		arg.ShareToken,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedFilename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedKey,
		&i.ShareToken,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, encryption_salt)
VALUES (?, ?, ?)
RETURNING id, email, password_hash, encryption_salt, created_at, updated_at
`

type CreateUserParams struct {
	Email          string `json:"email"`
	PasswordHash   string `json:"password_hash"`
	EncryptionSalt string `json:"encryption_salt"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.EncryptionSalt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EncryptionSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = ? AND user_id = ?
`

type DeleteFileParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteFile, arg.ID, arg.UserID)
	return err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
DELETE FROM files
WHERE id = ?
`

func (q *Queries) DeleteFileByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFileByID, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, encrypted_filename, file_path, file_size, encrypted_key, share_token, download_count, created_at, updated_at FROM files
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetFileByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetFileByID(ctx context.Context, arg GetFileByIDParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedFilename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedKey,
		&i.ShareToken,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByShareToken = `-- name: GetFileByShareToken :one
SELECT id, user_id, encrypted_filename, file_path, file_size, encrypted_key, share_token, download_count, created_at, updated_at FROM files
WHERE share_token = ?
LIMIT 1
`

func (q *Queries) GetFileByShareToken(ctx context.Context, shareToken sql.NullString) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByShareToken, shareToken)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedFilename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedKey,
		&i.ShareToken,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFilesByUserID = `-- name: GetFilesByUserID :many
SELECT id, user_id, encrypted_filename, file_path, file_size, encrypted_key, share_token, download_count, created_at, updated_at FROM files
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetFilesByUserID(ctx context.Context, userID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EncryptedFilename,
			&i.FilePath,
			&i.FileSize,
			&i.EncryptedKey,
			&i.ShareToken,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalStorageByUserID = `-- name: GetTotalStorageByUserID :one
SELECT COALESCE(SUM(file_size), 0) as total_storage
FROM files
WHERE user_id = ?
`

func (q *Queries) GetTotalStorageByUserID(ctx context.Context, userID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalStorageByUserID, userID)
	var total_storage interface{}
	err := row.Scan(&total_storage)
	return total_storage, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, encryption_salt, created_at, updated_at FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EncryptionSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, encryption_salt, created_at, updated_at FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EncryptionSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDownloadCountByToken = `-- name: IncrementDownloadCountByToken :one
UPDATE files
SET download_count = download_count + 1, updated_at = CURRENT_TIMESTAMP
WHERE share_token = ?
RETURNING id, user_id, encrypted_filename, file_path, file_size, encrypted_key, share_token, download_count, created_at, updated_at
`

func (q *Queries) IncrementDownloadCountByToken(ctx context.Context, shareToken sql.NullString) (File, error) {
	row := q.db.QueryRowContext(ctx, incrementDownloadCountByToken, shareToken)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedFilename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedKey,
		&i.ShareToken,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileShareToken = `-- name: UpdateFileShareToken :one
UPDATE files
SET share_token = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, encrypted_filename, file_path, file_size, encrypted_key, share_token, download_count, created_at, updated_at
`

type UpdateFileShareTokenParams struct {
	ShareToken sql.NullString `json:"share_token"`
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
}

func (q *Queries) UpdateFileShareToken(ctx context.Context, arg UpdateFileShareTokenParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFileShareToken, arg.ShareToken, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedFilename,
		&i.FilePath,
		&i.FileSize,
		&i.EncryptedKey,
		&i.ShareToken,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
