// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: src/relay/messages.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PBIncomingMessage represents messages received by the relay server from clients
type PBIncomingMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	RoomId            string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId          string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Pub               string                 `protobuf:"bytes,4,opt,name=pub,proto3" json:"pub,omitempty"`
	IvB64             string                 `protobuf:"bytes,7,opt,name=iv_b64,json=ivB64,proto3" json:"iv_b64,omitempty"`
	DataB64           string                 `protobuf:"bytes,8,opt,name=data_b64,json=dataB64,proto3" json:"data_b64,omitempty"`
	ChunkData         string                 `protobuf:"bytes,9,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	ChunkNum          int32                  `protobuf:"varint,10,opt,name=chunk_num,json=chunkNum,proto3" json:"chunk_num,omitempty"`
	EncryptedMetadata string                 `protobuf:"bytes,20,opt,name=encrypted_metadata,json=encryptedMetadata,proto3" json:"encrypted_metadata,omitempty"` // Encrypted metadata (name, total_size, is_folder, etc.)
	MetadataIv        string                 `protobuf:"bytes,21,opt,name=metadata_iv,json=metadataIv,proto3" json:"metadata_iv,omitempty"`                      // IV for encrypted_metadata
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PBIncomingMessage) Reset() {
	*x = PBIncomingMessage{}
	mi := &file_src_relay_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBIncomingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBIncomingMessage) ProtoMessage() {}

func (x *PBIncomingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_relay_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBIncomingMessage.ProtoReflect.Descriptor instead.
func (*PBIncomingMessage) Descriptor() ([]byte, []int) {
	return file_src_relay_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PBIncomingMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PBIncomingMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PBIncomingMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PBIncomingMessage) GetPub() string {
	if x != nil {
		return x.Pub
	}
	return ""
}

func (x *PBIncomingMessage) GetIvB64() string {
	if x != nil {
		return x.IvB64
	}
	return ""
}

func (x *PBIncomingMessage) GetDataB64() string {
	if x != nil {
		return x.DataB64
	}
	return ""
}

func (x *PBIncomingMessage) GetChunkData() string {
	if x != nil {
		return x.ChunkData
	}
	return ""
}

func (x *PBIncomingMessage) GetChunkNum() int32 {
	if x != nil {
		return x.ChunkNum
	}
	return 0
}

func (x *PBIncomingMessage) GetEncryptedMetadata() string {
	if x != nil {
		return x.EncryptedMetadata
	}
	return ""
}

func (x *PBIncomingMessage) GetMetadataIv() string {
	if x != nil {
		return x.MetadataIv
	}
	return ""
}

// PBOutgoingMessage represents messages sent by the relay server to clients
type PBOutgoingMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	From              string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Mnemonic          string                 `protobuf:"bytes,3,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	RoomId            string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Pub               string                 `protobuf:"bytes,5,opt,name=pub,proto3" json:"pub,omitempty"`
	IvB64             string                 `protobuf:"bytes,8,opt,name=iv_b64,json=ivB64,proto3" json:"iv_b64,omitempty"`
	DataB64           string                 `protobuf:"bytes,9,opt,name=data_b64,json=dataB64,proto3" json:"data_b64,omitempty"`
	ChunkData         string                 `protobuf:"bytes,10,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	ChunkNum          int32                  `protobuf:"varint,11,opt,name=chunk_num,json=chunkNum,proto3" json:"chunk_num,omitempty"`
	SelfId            string                 `protobuf:"bytes,13,opt,name=self_id,json=selfId,proto3" json:"self_id,omitempty"`
	Peers             []string               `protobuf:"bytes,14,rep,name=peers,proto3" json:"peers,omitempty"`
	Count             int32                  `protobuf:"varint,15,opt,name=count,proto3" json:"count,omitempty"`
	Error             string                 `protobuf:"bytes,16,opt,name=error,proto3" json:"error,omitempty"`
	EncryptedMetadata string                 `protobuf:"bytes,20,opt,name=encrypted_metadata,json=encryptedMetadata,proto3" json:"encrypted_metadata,omitempty"` // Encrypted metadata (name, total_size, is_folder, etc.)
	MetadataIv        string                 `protobuf:"bytes,21,opt,name=metadata_iv,json=metadataIv,proto3" json:"metadata_iv,omitempty"`                      // IV for encrypted_metadata
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PBOutgoingMessage) Reset() {
	*x = PBOutgoingMessage{}
	mi := &file_src_relay_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBOutgoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBOutgoingMessage) ProtoMessage() {}

func (x *PBOutgoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_relay_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBOutgoingMessage.ProtoReflect.Descriptor instead.
func (*PBOutgoingMessage) Descriptor() ([]byte, []int) {
	return file_src_relay_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PBOutgoingMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PBOutgoingMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PBOutgoingMessage) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *PBOutgoingMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PBOutgoingMessage) GetPub() string {
	if x != nil {
		return x.Pub
	}
	return ""
}

func (x *PBOutgoingMessage) GetIvB64() string {
	if x != nil {
		return x.IvB64
	}
	return ""
}

func (x *PBOutgoingMessage) GetDataB64() string {
	if x != nil {
		return x.DataB64
	}
	return ""
}

func (x *PBOutgoingMessage) GetChunkData() string {
	if x != nil {
		return x.ChunkData
	}
	return ""
}

func (x *PBOutgoingMessage) GetChunkNum() int32 {
	if x != nil {
		return x.ChunkNum
	}
	return 0
}

func (x *PBOutgoingMessage) GetSelfId() string {
	if x != nil {
		return x.SelfId
	}
	return ""
}

func (x *PBOutgoingMessage) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PBOutgoingMessage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PBOutgoingMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PBOutgoingMessage) GetEncryptedMetadata() string {
	if x != nil {
		return x.EncryptedMetadata
	}
	return ""
}

func (x *PBOutgoingMessage) GetMetadataIv() string {
	if x != nil {
		return x.MetadataIv
	}
	return ""
}

var File_src_relay_messages_proto protoreflect.FileDescriptor

const file_src_relay_messages_proto_rawDesc = "" +
	"\n" +
	"\x18src/relay/messages.proto\x12\x05relay\"\xad\x02\n" +
	"\x11PBIncomingMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x10\n" +
	"\x03pub\x18\x04 \x01(\tR\x03pub\x12\x15\n" +
	"\x06iv_b64\x18\a \x01(\tR\x05ivB64\x12\x19\n" +
	"\bdata_b64\x18\b \x01(\tR\adataB64\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\t \x01(\tR\tchunkData\x12\x1b\n" +
	"\tchunk_num\x18\n" +
	" \x01(\x05R\bchunkNum\x12-\n" +
	"\x12encrypted_metadata\x18\x14 \x01(\tR\x11encryptedMetadata\x12\x1f\n" +
	"\vmetadata_iv\x18\x15 \x01(\tR\n" +
	"metadataIv\"\x9b\x03\n" +
	"\x11PBOutgoingMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x1a\n" +
	"\bmnemonic\x18\x03 \x01(\tR\bmnemonic\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\x12\x10\n" +
	"\x03pub\x18\x05 \x01(\tR\x03pub\x12\x15\n" +
	"\x06iv_b64\x18\b \x01(\tR\x05ivB64\x12\x19\n" +
	"\bdata_b64\x18\t \x01(\tR\adataB64\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\n" +
	" \x01(\tR\tchunkData\x12\x1b\n" +
	"\tchunk_num\x18\v \x01(\x05R\bchunkNum\x12\x17\n" +
	"\aself_id\x18\r \x01(\tR\x06selfId\x12\x14\n" +
	"\x05peers\x18\x0e \x03(\tR\x05peers\x12\x14\n" +
	"\x05count\x18\x0f \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18\x10 \x01(\tR\x05error\x12-\n" +
	"\x12encrypted_metadata\x18\x14 \x01(\tR\x11encryptedMetadata\x12\x1f\n" +
	"\vmetadata_iv\x18\x15 \x01(\tR\n" +
	"metadataIvB$Z\"github.com/schollz/share/src/relayb\x06proto3"

var (
	file_src_relay_messages_proto_rawDescOnce sync.Once
	file_src_relay_messages_proto_rawDescData []byte
)

func file_src_relay_messages_proto_rawDescGZIP() []byte {
	file_src_relay_messages_proto_rawDescOnce.Do(func() {
		file_src_relay_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_relay_messages_proto_rawDesc), len(file_src_relay_messages_proto_rawDesc)))
	})
	return file_src_relay_messages_proto_rawDescData
}

var file_src_relay_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_relay_messages_proto_goTypes = []any{
	(*PBIncomingMessage)(nil), // 0: relay.PBIncomingMessage
	(*PBOutgoingMessage)(nil), // 1: relay.PBOutgoingMessage
}
var file_src_relay_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_relay_messages_proto_init() }
func file_src_relay_messages_proto_init() {
	if File_src_relay_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_relay_messages_proto_rawDesc), len(file_src_relay_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_relay_messages_proto_goTypes,
		DependencyIndexes: file_src_relay_messages_proto_depIdxs,
		MessageInfos:      file_src_relay_messages_proto_msgTypes,
	}.Build()
	File_src_relay_messages_proto = out.File
	file_src_relay_messages_proto_goTypes = nil
	file_src_relay_messages_proto_depIdxs = nil
}
