// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"database/sql"
)

type File struct {
	ID          string
	UserID      int64
	Filename    string
	Size        int64
	ContentType sql.NullString
	Data        []byte
	ShareToken  sql.NullString
	CreatedAt   sql.NullTime
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	StorageUsed  sql.NullInt64
	StorageLimit sql.NullInt64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
