// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package auth

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, user_id, filename, size, content_type, data, share_token)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, filename, size, content_type, share_token, created_at
`

type CreateFileParams struct {
	ID          string
	UserID      int64
	Filename    string
	Size        int64
	ContentType sql.NullString
	Data        []byte
	ShareToken  sql.NullString
}

type CreateFileRow struct {
	ID          string
	UserID      int64
	Filename    string
	Size        int64
	ContentType sql.NullString
	ShareToken  sql.NullString
	CreatedAt   sql.NullTime
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (CreateFileRow, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.Size,
		arg.ContentType,
		arg.Data,
		arg.ShareToken,
	)
	var i CreateFileRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.Size,
		&i.ContentType,
		&i.ShareToken,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES (?, ?)
RETURNING id, email, storage_used, storage_limit, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID           int64
	Email        string
	StorageUsed  sql.NullInt64
	StorageLimit sql.NullInt64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = ? AND user_id = ?
`

type DeleteFileParams struct {
	ID     string
	UserID int64
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteFile, arg.ID, arg.UserID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, filename, size, content_type, data, share_token, created_at
FROM files
WHERE id = ?
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.Size,
		&i.ContentType,
		&i.Data,
		&i.ShareToken,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByShareToken = `-- name: GetFileByShareToken :one
SELECT id, user_id, filename, size, content_type, data, share_token, created_at
FROM files
WHERE share_token = ?
`

func (q *Queries) GetFileByShareToken(ctx context.Context, shareToken sql.NullString) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByShareToken, shareToken)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.Size,
		&i.ContentType,
		&i.Data,
		&i.ShareToken,
		&i.CreatedAt,
	)
	return i, err
}

const getFileSizeByID = `-- name: GetFileSizeByID :one
SELECT size
FROM files
WHERE id = ? AND user_id = ?
`

type GetFileSizeByIDParams struct {
	ID     string
	UserID int64
}

func (q *Queries) GetFileSizeByID(ctx context.Context, arg GetFileSizeByIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFileSizeByID, arg.ID, arg.UserID)
	var size int64
	err := row.Scan(&size)
	return size, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, storage_used, storage_limit, created_at, updated_at
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, storage_used, storage_limit, created_at, updated_at
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesByUserID = `-- name: ListFilesByUserID :many
SELECT id, user_id, filename, size, content_type, share_token, created_at
FROM files
WHERE user_id = ?
ORDER BY created_at DESC
`

type ListFilesByUserIDRow struct {
	ID          string
	UserID      int64
	Filename    string
	Size        int64
	ContentType sql.NullString
	ShareToken  sql.NullString
	CreatedAt   sql.NullTime
}

func (q *Queries) ListFilesByUserID(ctx context.Context, userID int64) ([]ListFilesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesByUserIDRow
	for rows.Next() {
		var i ListFilesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.Size,
			&i.ContentType,
			&i.ShareToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileShareToken = `-- name: UpdateFileShareToken :exec
UPDATE files
SET share_token = ?
WHERE id = ? AND user_id = ?
`

type UpdateFileShareTokenParams struct {
	ShareToken sql.NullString
	ID         string
	UserID     int64
}

func (q *Queries) UpdateFileShareToken(ctx context.Context, arg UpdateFileShareTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateFileShareToken, arg.ShareToken, arg.ID, arg.UserID)
	return err
}

const updateUserStorageUsed = `-- name: UpdateUserStorageUsed :exec
UPDATE users
SET storage_used = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserStorageUsedParams struct {
	StorageUsed sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateUserStorageUsed(ctx context.Context, arg UpdateUserStorageUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStorageUsed, arg.StorageUsed, arg.ID)
	return err
}
